In [163]:
import numpy as np 
import pandas as pd 
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split
from tensorflow.keras import layers

In [164]:
df = pd.DataFrame({
    "soil_moisture": [0.10, 0.15, 0.20, 0.25, 0.40, 0.60, 0.35, 0.18,
                      0.45, 0.05, 0.80, 0.27, 0.55, 0.70, 0.12, 0.30],
    "temperature_c": [34, 30, 26, 22, 28, 30, 19, 22,
                      35, 24, 33, 33, 21, 25, 20, 29],
    "sunlight_hours": [9, 8, 7, 4, 8, 10, 3, 10,
                       12, 5, 9, 11, 2, 6, 1, 9],
    "needs_water": [1, 1, 1, 0, 0, 0, 0, 1,
                    0, 1, 0, 1, 0, 0, 1, 1]
})

In [165]:
df

    soil_moisture  temperature_c  sunlight_hours  needs_water
0            0.10             34               9            1
1            0.15             30               8            1
2            0.20             26               7            1
3            0.25             22               4            0
4            0.40             28               8            0
5            0.60             30              10            0
6            0.35             19               3            0
7            0.18             22              10            1
8            0.45             35              12            0
9            0.05             24               5            1
10           0.80             33               9            0
11           0.27             33              11            1
12           0.55             21               2            0
13           0.70             25               6            0
14           0.12             20               1            1
15           0.30             29               9            1

In [166]:
X = df.drop("needs_water",axis=1)
y = df["needs_water"]

In [167]:
X_min = X.min()
X_max = X.max()
X_scaled = (X-X_min) / (X_max - X_min + 1e-8)
X_scaled

    soil_moisture  temperature_c  sunlight_hours
0        0.066667         0.9375        0.727273
1        0.133333         0.6875        0.636364
2        0.200000         0.4375        0.545455
3        0.266667         0.1875        0.272727
4        0.466667         0.5625        0.636364
5        0.733333         0.6875        0.818182
6        0.400000         0.0000        0.181818
7        0.173333         0.1875        0.818182
8        0.533333         1.0000        1.000000
9        0.000000         0.3125        0.363636
10       1.000000         0.8750        0.727273
11       0.293333         0.8750        0.909091
12       0.666667         0.1250        0.090909
13       0.866667         0.3750        0.454545
14       0.093333         0.0625        0.000000
15       0.333333         0.6250        0.727273

In [168]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.25, random_state=42)

In [169]:
model = keras.Sequential([
    layers.Input(shape=(X_train.shape[1],)),
    layers.Dense(8,activation="relu"),
    layers.Dense(1,activation="sigmoid")
])

In [170]:
# next step is to compile where we tell which optimizer and loss fn to use
model.compile(optimizer="sgd", loss="binary_crossentropy",metrics=["accuracy"])

In [171]:
# here we will give data in arrays no fd as it works with arrays
history = model.fit(
    X_train.values,y_train.values,
    validation_data = (X_test.values, y_test.values),
    epochs = 100, batch_size = 4, verbose = 1
)

Epoch 1/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.4167 - loss: 0.6933 - val_accuracy: 0.5000 - val_loss: 0.6938
Epoch 2/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5000 - loss: 0.6918 - val_accuracy: 0.5000 - val_loss: 0.6948
Epoch 3/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5000 - loss: 0.6894 - val_accuracy: 0.5000 - val_loss: 0.6959
Epoch 4/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5000 - loss: 0.6889 - val_accuracy: 0.5000 - val_loss: 0.6968
Epoch 5/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5000 - loss: 0.6867 - val_accuracy: 0.5000 - val_loss: 0.6976
Epoch 6/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5000 - loss: 0.6846 - val_accuracy: 0.5000 - val_loss: 0.6983
Epoch 7/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5000 - loss: 0.6841 - val_accuracy: 0.5000 - val_loss: 0.6991
Epoch 8/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5000 - loss: 0.6818 - val_accuracy: 0.5000 - val_loss: 0.6997
Epoch 9/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5000 - loss: 0.6804 - val_accuracy: 0.5000 - val_loss: 0.7004
Epoch 10/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5000 - loss: 0.6791 - val_accuracy: 0.5000 - val_loss: 0.7011
Epoch 11/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.4167 - loss: 0.6783 - val_accuracy: 0.2500 - val_loss: 0.7017
Epoch 12/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.4167 - loss: 0.6771 - val_accuracy: 0.2500 - val_loss: 0.7023
Epoch 13/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.4167 - loss: 0.6764 - val_accuracy: 0.2500 - val_loss: 0.7029
Epoch 14/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.3333 - loss: 0.6750 - val_accuracy: 0.5000 - val_loss: 0.7036
Epoch 15/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.4167 - loss: 0.6740 - val_accuracy: 0.5000 - val_loss: 0.7042
Epoch 16/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.4167 - loss: 0.6724 - val_accuracy: 0.5000 - val_loss: 0.7048
Epoch 17/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.4167 - loss: 0.6705 - val_accuracy: 0.5000 - val_loss: 0.7054
Epoch 18/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.4167 - loss: 0.6701 - val_accuracy: 0.5000 - val_loss: 0.7060
Epoch 19/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.4167 - loss: 0.6679 - val_accuracy: 0.5000 - val_loss: 0.7065
Epoch 20/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.4167 - loss: 0.6689 - val_accuracy: 0.5000 - val_loss: 0.7071
Epoch 21/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.4167 - loss: 0.6656 - val_accuracy: 0.5000 - val_loss: 0.7077
Epoch 22/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.4167 - loss: 0.6648 - val_accuracy: 0.5000 - val_loss: 0.7082
Epoch 23/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5000 - loss: 0.6640 - val_accuracy: 0.2500 - val_loss: 0.7087
Epoch 24/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.4167 - loss: 0.6624 - val_accuracy: 0.2500 - val_loss: 0.7093
Epoch 25/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.4167 - loss: 0.6610 - val_accuracy: 0.2500 - val_loss: 0.7098
Epoch 26/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.4167 - loss: 0.6599 - val_accuracy: 0.2500 - val_loss: 0.7103
Epoch 27/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.4167 - loss: 0.6589 - val_accuracy: 0.2500 - val_loss: 0.7107
Epoch 28/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.4167 - loss: 0.6604 - val_accuracy: 0.2500 - val_loss: 0.7111
Epoch 29/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5833 - loss: 0.6579 - val_accuracy: 0.2500 - val_loss: 0.7115
Epoch 30/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5833 - loss: 0.6562 - val_accuracy: 0.2500 - val_loss: 0.7119
Epoch 31/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5000 - loss: 0.6554 - val_accuracy: 0.2500 - val_loss: 0.7123
Epoch 32/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5833 - loss: 0.6536 - val_accuracy: 0.2500 - val_loss: 0.7127
Epoch 33/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5833 - loss: 0.6533 - val_accuracy: 0.2500 - val_loss: 0.7131
Epoch 34/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5833 - loss: 0.6515 - val_accuracy: 0.2500 - val_loss: 0.7134
Epoch 35/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5000 - loss: 0.6517 - val_accuracy: 0.2500 - val_loss: 0.7139
Epoch 36/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5833 - loss: 0.6499 - val_accuracy: 0.2500 - val_loss: 0.7142
Epoch 37/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.5833 - loss: 0.6495 - val_accuracy: 0.2500 - val_loss: 0.7145
Epoch 38/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.5833 - loss: 0.6473 - val_accuracy: 0.2500 - val_loss: 0.7149
Epoch 39/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.5833 - loss: 0.6465 - val_accuracy: 0.2500 - val_loss: 0.7153
Epoch 40/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.5833 - loss: 0.6457 - val_accuracy: 0.2500 - val_loss: 0.7157
Epoch 41/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.5833 - loss: 0.6439 - val_accuracy: 0.2500 - val_loss: 0.7161
Epoch 42/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5833 - loss: 0.6427 - val_accuracy: 0.2500 - val_loss: 0.7165
Epoch 43/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5833 - loss: 0.6419 - val_accuracy: 0.2500 - val_loss: 0.7169
Epoch 44/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5833 - loss: 0.6411 - val_accuracy: 0.2500 - val_loss: 0.7173
Epoch 45/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5833 - loss: 0.6403 - val_accuracy: 0.2500 - val_loss: 0.7176
Epoch 46/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.5833 - loss: 0.6382 - val_accuracy: 0.2500 - val_loss: 0.7180
Epoch 47/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5833 - loss: 0.6371 - val_accuracy: 0.2500 - val_loss: 0.7184
Epoch 48/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.5833 - loss: 0.6356 - val_accuracy: 0.2500 - val_loss: 0.7188
Epoch 49/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5833 - loss: 0.6341 - val_accuracy: 0.2500 - val_loss: 0.7192
Epoch 50/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5833 - loss: 0.6329 - val_accuracy: 0.2500 - val_loss: 0.7195
Epoch 51/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5833 - loss: 0.6322 - val_accuracy: 0.2500 - val_loss: 0.7199
Epoch 52/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5833 - loss: 0.6307 - val_accuracy: 0.2500 - val_loss: 0.7203
Epoch 53/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5833 - loss: 0.6288 - val_accuracy: 0.2500 - val_loss: 0.7206
Epoch 54/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5833 - loss: 0.6283 - val_accuracy: 0.5000 - val_loss: 0.7210
Epoch 55/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5833 - loss: 0.6262 - val_accuracy: 0.5000 - val_loss: 0.7212
Epoch 56/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5833 - loss: 0.6249 - val_accuracy: 0.5000 - val_loss: 0.7212
Epoch 57/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5833 - loss: 0.6240 - val_accuracy: 0.5000 - val_loss: 0.7213
Epoch 58/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5833 - loss: 0.6226 - val_accuracy: 0.5000 - val_loss: 0.7213
Epoch 59/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.5833 - loss: 0.6215 - val_accuracy: 0.5000 - val_loss: 0.7214
Epoch 60/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5833 - loss: 0.6207 - val_accuracy: 0.5000 - val_loss: 0.7215
Epoch 61/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5833 - loss: 0.6195 - val_accuracy: 0.5000 - val_loss: 0.7215
Epoch 62/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5833 - loss: 0.6194 - val_accuracy: 0.5000 - val_loss: 0.7215
Epoch 63/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5833 - loss: 0.6181 - val_accuracy: 0.5000 - val_loss: 0.7216
Epoch 64/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5833 - loss: 0.6158 - val_accuracy: 0.5000 - val_loss: 0.7216
Epoch 65/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5833 - loss: 0.6166 - val_accuracy: 0.5000 - val_loss: 0.7216
Epoch 66/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5833 - loss: 0.6138 - val_accuracy: 0.5000 - val_loss: 0.7217
Epoch 67/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5833 - loss: 0.6138 - val_accuracy: 0.5000 - val_loss: 0.7217
Epoch 68/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5833 - loss: 0.6126 - val_accuracy: 0.5000 - val_loss: 0.7218
Epoch 69/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5833 - loss: 0.6121 - val_accuracy: 0.5000 - val_loss: 0.7218
Epoch 70/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5833 - loss: 0.6097 - val_accuracy: 0.5000 - val_loss: 0.7218
Epoch 71/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5833 - loss: 0.6085 - val_accuracy: 0.5000 - val_loss: 0.7218
Epoch 72/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5833 - loss: 0.6077 - val_accuracy: 0.5000 - val_loss: 0.7220
Epoch 73/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.5833 - loss: 0.6063 - val_accuracy: 0.5000 - val_loss: 0.7221
Epoch 74/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5833 - loss: 0.6044 - val_accuracy: 0.5000 - val_loss: 0.7222
Epoch 75/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5833 - loss: 0.6029 - val_accuracy: 0.5000 - val_loss: 0.7222
Epoch 76/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5833 - loss: 0.6013 - val_accuracy: 0.5000 - val_loss: 0.7223
Epoch 77/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5833 - loss: 0.6001 - val_accuracy: 0.5000 - val_loss: 0.7224
Epoch 78/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5833 - loss: 0.5982 - val_accuracy: 0.5000 - val_loss: 0.7225
Epoch 79/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5833 - loss: 0.5967 - val_accuracy: 0.5000 - val_loss: 0.7225
Epoch 80/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5000 - loss: 0.5962 - val_accuracy: 0.5000 - val_loss: 0.7226
Epoch 81/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6667 - loss: 0.5937 - val_accuracy: 0.5000 - val_loss: 0.7225
Epoch 82/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6667 - loss: 0.5921 - val_accuracy: 0.5000 - val_loss: 0.7226
Epoch 83/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6667 - loss: 0.5907 - val_accuracy: 0.5000 - val_loss: 0.7225
Epoch 84/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5833 - loss: 0.5891 - val_accuracy: 0.7500 - val_loss: 0.7225
Epoch 85/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5833 - loss: 0.5890 - val_accuracy: 0.7500 - val_loss: 0.7226
Epoch 86/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5833 - loss: 0.5868 - val_accuracy: 0.7500 - val_loss: 0.7225
Epoch 87/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5833 - loss: 0.5853 - val_accuracy: 0.7500 - val_loss: 0.7223
Epoch 88/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5833 - loss: 0.5832 - val_accuracy: 0.7500 - val_loss: 0.7223
Epoch 89/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5833 - loss: 0.5821 - val_accuracy: 0.7500 - val_loss: 0.7218
Epoch 90/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5833 - loss: 0.5806 - val_accuracy: 0.7500 - val_loss: 0.7212
Epoch 91/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5833 - loss: 0.5791 - val_accuracy: 0.7500 - val_loss: 0.7207
Epoch 92/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5833 - loss: 0.5783 - val_accuracy: 0.7500 - val_loss: 0.7199
Epoch 93/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5833 - loss: 0.5764 - val_accuracy: 0.7500 - val_loss: 0.7194
Epoch 94/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5833 - loss: 0.5753 - val_accuracy: 0.7500 - val_loss: 0.7188
Epoch 95/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5833 - loss: 0.5735 - val_accuracy: 0.7500 - val_loss: 0.7182
Epoch 96/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5833 - loss: 0.5723 - val_accuracy: 0.7500 - val_loss: 0.7175
Epoch 97/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5833 - loss: 0.5712 - val_accuracy: 0.7500 - val_loss: 0.7169
Epoch 98/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5833 - loss: 0.5708 - val_accuracy: 0.7500 - val_loss: 0.7160
Epoch 99/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5833 - loss: 0.5671 - val_accuracy: 0.7500 - val_loss: 0.7154
Epoch 100/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5833 - loss: 0.5663 - val_accuracy: 0.7500 - val_loss: 0.7147